import { sql } from 'drizzle-orm';
import {
	index,
	json,
	timestamp,
	uniqueIndex,
	varchar,
} from 'drizzle-orm/mysql-core';
import type { MySqlTableFn } from 'drizzle-orm/mysql-core';

import { getCourseBuilderSchema } from '@coursebuilder/adapter-drizzle/mysql';

import { mysqlTable } from './mysql-table';

export function getUsersSchema(mysqlTable: MySqlTableFn) {
	return mysqlTable(
		'User',
		{
			id: varchar('id', { length: 255 }).notNull().primaryKey(),
			name: varchar('name', { length: 255 }),
			role: varchar('role', { length: 191 }).notNull().default('user'),
			email: varchar('email', { length: 255 }).notNull().unique(),
			fields: json('fields').$type<Record<string, any>>().default({}),
			externalId: varchar('externalId', { length: 255 }).generatedAlwaysAs(
				sql`(fields->>'$.externalId')`,
				{ mode: 'stored' },
			),
			emailVerified: timestamp('emailVerified', {
				mode: 'date',
				fsp: 3,
			}),
			image: varchar('image', { length: 255 }),
			createdAt: timestamp('createdAt', {
				mode: 'date',
				fsp: 3,
			}).default(sql`CURRENT_TIMESTAMP(3)`),
		},
		(user) => ({
			emailIdx: index('email_idx').on(user.email),
			externalIdIdx: uniqueIndex('external_id_idx').on(user.externalId),
			roleIdx: index('role_idx').on(user.role),
			createdAtIdx: index('created_at_idx').on(user.createdAt),
		}),
	);
}

export const {
	accounts,
	accountsRelations,
	profiles,
	profilesRelations,
	permissions,
	permissionsRelations,
	rolePermissions,
	rolePermissionsRelations,
	roles,
	rolesRelations,
	sessions,
	sessionsRelations,
	userPermissions,
	userPermissionsRelations,
	userRoles,
	userRolesRelations,
	users,
	usersRelations,
	verificationTokens,
	coupon,
	couponRelations,
	lessonProgress,
	merchantAccount,
	merchantCharge,
	merchantChargeRelations,
	merchantEvents,
	merchantEventsRelations,
	merchantCoupon,
	merchantCustomer,
	merchantPrice,
	merchantProduct,
	merchantSession,
	prices,
	products,
	productRelations,
	purchases,
	purchaseRelations,
	purchaseUserTransfer,
	purchaseUserTransferRelations,
	communicationChannel,
	communicationPreferenceTypes,
	communicationPreferences,
	communicationPreferencesRelations,
	questionResponse,
	questionResponseRelations,
	contentContributions,
	contentContributionRelations,
	contentResource,
	contentResourceRelations,
	contentResourceTag,
	contentResourceTagRelations,
	tag,
	tagRelations,
	tagTag,
	tagTagRelations,
	contentResourceVersion,
	contentResourceVersionRelations,
	contentResourceResource,
	contentResourceResourceRelations,
	contributionTypes,
	contributionTypesRelations,
	resourceProgress,
	contentResourceProduct,
	contentResourceProductRelations,
	upgradableProducts,
	upgradableProductsRelations,
	comments,
	commentsRelations,
	userPrefs,
	userPrefsRelations,
	organization,
	organizationRelations,
	organizationMemberships,
	organizationMembershipRelations,
	organizationMembershipRoles,
	organizationMembershipRolesRelations,
	merchantSubscription,
	merchantSubscriptionRelations,
	subscription,
	subscriptionRelations,
	deviceVerifications,
	deviceVerificationRelations,
	deviceAccessToken,
	deviceAccessTokenRelations,
	entitlements,
	entitlementsRelations,
	entitlementTypes,
} = getCourseBuilderSchema(mysqlTable, { getUsersSchema });
